import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {
    width: '100%',
    marginBottom: 50,
  },
  box1: {
    flexDirection: 'row',
    width: '100%',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 15,
  },
  title: {
    fontSize: 25,
    fontWeight: '600',
    color: '#3F3535',
    lineHeight: 40,
    marginLeft: 15,
  },
  box1_title: {
    fontSize: 15,
    color: '#C8C8C8',
    lineHeight: 40,
  },
  border: {
    width: '100%',
    borderWidth: 1,
    borderColor: '#7171712d',
    marginTop: 14,
    marginBottom: 14,
  },
  box2: {
    width: '100%',
    paddingHorizontal: 15,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  box2_title_now: {
    fontSize: 24,
    lineHeight: 40,
  },
  box2_title_old: {
    fontSize: 18,
    lineHeight: 40,
    color: '#C8C8C8',
  },
  box3: {
    width: '100%',
    paddingHorizontal: 15,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  box3_title: {
    fontSize: 17,
    fontWeight: '700',
    lineHeight: 40,
  },
  box4: {
    paddingHorizontal: 15,
  },
  box4_title: {
    fontWeight: '700',
    fontSize: 17,
    lineHeight: 40,
  },
  box4_content: {
    position: 'relative',
    marginBottom: 13,
  },
  content_title: {
    fontWeight: '500',
    fontSize: 15,
    lineHeight: 20,
    color: '#C8C8C8',
  },
  colors: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    marginTop: 11,
  },
  active: {
    width: 92,
    height: 33,
    borderRadius: 25,
    borderWidth: 1,
    borderColor: '#84A9C0',
    borderStyle: 'solid',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 5,
  },
  active_title: {
    fontSize: 15,
    fontWeight: '400',
    lineHeight: 20,
    color: '#84A9C0',
  },
  box_noactive: {
    width: '100%',
    marginTop: 9,
    zIndex: 3,
    paddingBottom: 24,
  },
  value: {
    flexDirection: 'row',
    width: 163,
    height: 55,
    backgroundColor: '#d1d1d1',
    borderRadius: 45,
    alignItems: 'center',
    justifyContent: 'space-around',
  },
  box5: {
    width: '100%',
    paddingHorizontal: 15,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  box6: {
    width: '100%',
    paddingHorizontal: 15,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  brend: {
    fontSize: 17,
    fontWeight: '600',
    lineHeight: 40,
    color: '#3F3535',
  },
  chiaro: {
    fontSize: 17,
    fontWeight: '600',
    lineHeight: 40,
    color: '#C8C8C8',
  },
  render_container: {
    position: 'relative',
    width: '100%',
    marginTop: 29,
    flexWrap: 'wrap',
    flexDirection: 'row',
  },
  button: {
    marginTop: 57,
    paddingHorizontal: 15,
  },
  goBack: {
    position: 'absolute',
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    top: 28,
  },
  icons: {
    width: 50,
    height: 44,
    backgroundColor: '#84A9C0',
    borderRadius: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
